### ISSUE TITLE
bash code should be in a %%bash cell to be run-able

### ISSUE THREAD

**Issue by koudyk** [neurostuff/ohbm2021-nimare-tutorial#13]
@tsalo , I see that you made the bash code for downloading the data part of a markdown cell in the tutorial notebook. Did you have a particular reason? If we want it to be run-able, I think it needs to be a code cell. 

The `%%bash` on the top line of the cell makes the cell able to execute bash code (instead of the python code, which is the default).

**Comment by tsalo** [comment]
I added some instructions for copying to a runnable cell, but I wanted to make sure that folks wouldn't accidentally run the cell in Binder. I figured Markdown + instructions would be the best compromise.

**Comment by koudyk** [comment]
I see, sorry, I didn't read the instructions carefully. Sounds good! 

Just curious - why would it be a problem in binder? I tried to make it so it would only download the data if it detected that it wasn't already there. But I wasn't able to test it in binder yet.

**Comment by tsalo** [comment]
I saw the if statement, so I don't think it would be a problem to run the cell in Binder, but I feel like I would have to explain the code a bit if we were running it, and since it's not necessary for the Binder-based tutorial...

That said, I will probably reuse this notebook for Neurohackademy, and I don't know if we'll use Binder for that, so I may switch it back to a code cell after tomorrow.

**Comment by koudyk** [comment]
Cool, okay, then I'll let you close this now or when you've decided what to do.
